# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'market_dialog.ui'
#
# Created: Tue Oct 27 18:04:27 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1920, 1080)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        self.lbl_Usyd_logo = QtGui.QLabel(Dialog)
        self.lbl_Usyd_logo.setGeometry(QtCore.QRect(20, 10, 200, 70))
        self.lbl_Usyd_logo.setText(_fromUtf8(""))
        self.lbl_Usyd_logo.setPixmap(QtGui.QPixmap(_fromUtf8("images/usyd_logo.png")))
        self.lbl_Usyd_logo.setScaledContents(True)
        self.lbl_Usyd_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Usyd_logo.setObjectName(_fromUtf8("lbl_Usyd_logo"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(700, 0, 540, 85))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 90, 1914, 254))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbl_user = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_user.setText(_fromUtf8(""))
        self.lbl_user.setPixmap(QtGui.QPixmap(_fromUtf8("images/user.png")))
        self.lbl_user.setScaledContents(False)
        self.lbl_user.setObjectName(_fromUtf8("lbl_user"))
        self.horizontalLayout.addWidget(self.lbl_user)
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_algo = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_algo.setText(_fromUtf8(""))
        self.lbl_algo.setPixmap(QtGui.QPixmap(_fromUtf8("images/algorithm3.png")))
        self.lbl_algo.setScaledContents(False)
        self.lbl_algo.setObjectName(_fromUtf8("lbl_algo"))
        self.horizontalLayout.addWidget(self.lbl_algo)
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lbl_resource = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_resource.setText(_fromUtf8(""))
        self.lbl_resource.setPixmap(QtGui.QPixmap(_fromUtf8("images/computer.png")))
        self.lbl_resource.setScaledContents(False)
        self.lbl_resource.setObjectName(_fromUtf8("lbl_resource"))
        self.horizontalLayout.addWidget(self.lbl_resource)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.horizontalFrame_2 = QtGui.QFrame(Dialog)
        self.horizontalFrame_2.setGeometry(QtCore.QRect(0, 830, 1911, 231))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_2.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_2.setSizePolicy(sizePolicy)
        self.horizontalFrame_2.setObjectName(_fromUtf8("horizontalFrame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lbl_market = QtGui.QLabel(self.horizontalFrame_2)
        self.lbl_market.setText(_fromUtf8(""))
        self.lbl_market.setPixmap(QtGui.QPixmap(_fromUtf8("images/scale.png")))
        self.lbl_market.setScaledContents(False)
        self.lbl_market.setObjectName(_fromUtf8("lbl_market"))
        self.horizontalLayout_2.addWidget(self.lbl_market)
        self.label_11 = QtGui.QLabel(self.horizontalFrame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label = QtGui.QLabel(self.horizontalFrame_2)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("images/architecture_s.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.label_12 = QtGui.QLabel(self.horizontalFrame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_2.addWidget(self.label_12)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalFrame = QtGui.QFrame(self.horizontalFrame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setObjectName(_fromUtf8("verticalFrame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lbl_demandgui = QtGui.QLabel(self.verticalFrame)
        self.lbl_demandgui.setFrameShape(QtGui.QFrame.Box)
        self.lbl_demandgui.setText(_fromUtf8(""))
        self.lbl_demandgui.setPixmap(QtGui.QPixmap(_fromUtf8("images/system_s.png")))
        self.lbl_demandgui.setScaledContents(True)
        self.lbl_demandgui.setObjectName(_fromUtf8("lbl_demandgui"))
        self.verticalLayout_2.addWidget(self.lbl_demandgui)
        self.horizontalLayout_2.addWidget(self.verticalFrame)
        self.label_13 = QtGui.QLabel(self.horizontalFrame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_2.addWidget(self.label_13)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 330, 2001, 491))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_algo_description = QtGui.QLabel(self.frame)
        self.label_algo_description.setGeometry(QtCore.QRect(540, 410, 471, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_algo_description.setFont(font)
        self.label_algo_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_algo_description.setObjectName(_fromUtf8("label_algo_description"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(1010, 30, 891, 451))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_ts_description = QtGui.QLabel(self.frame)
        self.label_ts_description.setGeometry(QtCore.QRect(540, 320, 471, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_ts_description.setFont(font)
        self.label_ts_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_ts_description.setWordWrap(True)
        self.label_ts_description.setObjectName(_fromUtf8("label_ts_description"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(1710, 10, 191, 41))
        self.label_7.setFrameShape(QtGui.QFrame.Box)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_ts_description_2 = QtGui.QLabel(self.frame)
        self.label_ts_description_2.setGeometry(QtCore.QRect(590, 10, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_ts_description_2.setFont(font)
        self.label_ts_description_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_ts_description_2.setWordWrap(True)
        self.label_ts_description_2.setObjectName(_fromUtf8("label_ts_description_2"))
        self.lbl_scoretable = QtGui.QLabel(self.frame)
        self.lbl_scoretable.setGeometry(QtCore.QRect(610, 40, 353, 271))
        self.lbl_scoretable.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_scoretable.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_scoretable.setObjectName(_fromUtf8("lbl_scoretable"))
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 340, 501, 471))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.list_ts = QtGui.QListWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.list_ts.setFont(font)
        self.list_ts.setObjectName(_fromUtf8("list_ts"))
        self.gridLayout.addWidget(self.list_ts, 3, 0, 1, 1)
        self.list_algos = QtGui.QListWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.list_algos.setFont(font)
        self.list_algos.setObjectName(_fromUtf8("list_algos"))
        self.gridLayout.addWidget(self.list_algos, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_2.setText(_translate("Dialog", "Prediction Market", None))
        self.label_3.setText(_translate("Dialog", "Democratising Data Sciences Through Competition", None))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">The User</span></p><p><span style=\" font-size:12pt;\">• Complex data needs complex modeling.</span></p><p><span style=\" font-size:12pt;\">• Data science expertise required to analyse data.</span></p><p><span style=\" font-size:12pt;\">• Statistician and business intelligence tools <br/>    are expensive.</span></p><p><span style=\" font-size:12pt;\">• Free software available but requires knowledge.</span></p><p><span style=\" font-size:12pt;\">• May worry about intellectual property.</span></p><p><br/></p></body></html>", None))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">The Data Scientist</span></p><p><span style=\" font-size:12pt;\">• Has knowledge of the machile learning tools.</span></p><p><span style=\" font-size:12pt;\">• Develops new algorithms.</span></p><p><span style=\" font-size:12pt;\">• Is looking for data to test algorithms.</span></p><p><span style=\" font-size:12pt;\">• May require external data to improve<br/>    predictions.</span></p><p><span style=\" font-size:12pt;\">• May worry about intellectual property.</span><br/></p></body></html>", None))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Computational Resources</span></p><p><span style=\" font-size:12pt;\">• Provide low level storage and processing<br>&nbsp;&nbsp;&nbsp; interfaces.</span></p><p><span style=\" font-size:12pt;\">• Maintenance required by another party.</span></p><p><span style=\" font-size:12pt;\">• It is not free, but is cheap if bought in bulk.</span></p><p><br/></p><p><br/></p></body></html>", None))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">A market for users and developers</span></p><p><span style=\" font-size:12pt;\">• Allowing developers and users to search and<br/>   advertise, like an “App Store”.</span></p><p><span style=\" font-size:12pt;\">• Competition to provide better algorithms.</span></p><p><span style=\" font-size:12pt;\">• Fair pricing of algorithms based on their<br/>   performance.</span></p><p><span style=\" font-size:12pt;\">• Third party to keep intellectual property safe.</span></p><p><br/></p><p><br/></p></body></html>", None))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Everything is on the cloud</span></p><p><span style=\" font-size:12pt;\">• Web-based and JSON interface, for<br/>   man and machine.</span></p><p><span style=\" font-size:12pt;\">• On demand and scalable.</span></p><p><span style=\" font-size:12pt;\">• Better use of computational resources.</span></p><p><span style=\" font-size:12pt;\">• Many open source algorithms to<br/>   start with.</span></p><p><br/></p><p><br/></p></body></html>", None))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Real-world Demo</span></p><p><span style=\" font-size:12pt;\">• Forecasting electricity demand<br/>   and solar generation.</span></p><p><span style=\" font-size:12pt;\">• Scheduling a battery to <br/>   control local demand.</span></p><p><span style=\" font-size:12pt;\">• See Intelligent Energy <br/>   Network Section.</span><br/></p><p><br/></p></body></html>", None))
        self.label_algo_description.setText(_translate("Dialog", "Select an algorithm for more information.", None))
        self.label_ts_description.setText(_translate("Dialog", "Select a time-series to begin.", None))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Legend:</span>\n"
"<span style=\" font-size:12pt; color:#0000ff;\">Observations</span><br/>\n"
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n"
"<span style=\" font-size:12pt; color:#ff0000;\">Predictions </span></p></body></html>", None))
        self.label_ts_description_2.setText(_translate("Dialog", "Prediction error (Less is better)", None))
        self.lbl_scoretable.setText(_translate("Dialog", "TextLabel", None))
        self.label_5.setText(_translate("Dialog", "Prediction Techniques", None))
        self.label_4.setText(_translate("Dialog", "List of available data", None))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Automatic model selection demo:</span></p><ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Data and algorithms on the server are queried.</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">For each time-series data, different prediction techniques are tested and compared.</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Forecast errors are computed for different periods and are accumulated.</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The technique with minimum error is selected as the best forecaster.</li></ol></body></html>", None))

